# Generated by Django 4.2.16 on 2024-11-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='discharged_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
